## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
# 設定 data_path
dir_data = 'C:/Users/User/Documents/GitHub/2nd_ML100Days/data/Part01'

In [4]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: C:/Users/User/Documents/GitHub/2nd_ML100Days/data/Part01\application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [8]:
row=len(app_train.index)
print("row number of the data is : "+str(row))
col=len(app_train.columns)
print("column number of the data is : "+str(col))

row number of the data is : 307511
column number of the data is : 122

#### 列出所有欄位

In [9]:
l=app_train.axes
l

[RangeIndex(start=0, stop=307511, step=1),
 Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
        'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
        'AMT_CREDIT', 'AMT_ANNUITY',
        ...
        'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
        'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
        'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
        'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
        'AMT_REQ_CREDIT_BUREAU_YEAR'],
       dtype='object', length=122)]

#### 截取部分資料

In [17]:
app_train.loc[k-1]  #擷取第k名乘客(第k列)資料

app_train.loc[app_train['FLAG_OWN_CAR'] == 'Y'] #擷取FLAG_OWN_CA欄中值為Y的資料

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
6,100009,0,Cash loans,F,Y,Y,1,171000.0,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.0,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
15,100019,0,Cash loans,M,Y,Y,0,157500.0,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.0,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.0,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
24,100029,0,Cash loans,M,Y,N,2,135000.0,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.0,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
33,100039,0,Cash loans,M,Y,N,1,360000.0,733315.5,39069.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
39,100046,0,Revolving loans,M,Y,Y,0,180000.0,540000.0,27000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
49,100056,0,Cash loans,M,Y,Y,0,360000.0,1506816.0,49927.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
51,100059,0,Cash loans,M,Y,Y,1,540000.0,675000.0,34596.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
52,100060,0,Cash loans,M,Y,N,0,76500.0,454500.0,14661.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
54,100062,0,Cash loans,M,Y,N,0,81000.0,675000.0,32472.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
58,100069,0,Cash loans,M,Y,Y,1,360000.0,640458.0,27265.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
62,100073,0,Cash loans,M,Y,Y,0,324000.0,1130760.0,40189.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
64,100076,0,Cash loans,M,Y,N,0,180000.0,315000.0,9679.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
66,100078,0,Cash loans,F,Y,Y,0,180000.0,1035000.0,43983.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
69,100081,0,Cash loans,M,Y,N,0,180000.0,450000.0,21109.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
71,100083,0,Cash loans,M,Y,Y,0,103500.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
82,100097,0,Cash loans,M,Y,Y,0,157500.0,760225.5,30280.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
83,100098,0,Revolving loans,M,Y,N,0,225000.0,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
85,100100,0,Cash loans,M,Y,Y,2,202500.0,796396.5,38443.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
86,100101,0,Cash loans,F,Y,Y,0,202500.0,343377.0,22072.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
92,100110,0,Cash loans,M,Y,Y,3,135000.0,373140.0,25065.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
93,100111,0,Cash loans,F,Y,N,1,112500.0,862560.0,27954.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
94,100112,1,Cash loans,M,Y,Y,0,315000.0,953460.0,64107.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
95,100113,0,Cash loans,M,Y,N,0,76500.0,135000.0,6696.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307408,456141,0,Cash loans,F,Y,Y,1,112500.0,237024.0,18855.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307414,456147,0,Cash loans,F,Y,Y,2,90000.0,1078200.0,31653.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307415,456148,0,Cash loans,M,Y,Y,0,180000.0,589045.5,30204.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307416,456149,0,Cash loans,F,Y,Y,0,90000.0,327024.0,21982.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307421,456154,0,Cash loans,M,Y,Y,0,157500.0,144000.0,9751.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307425,456158,0,Revolving loans,M,Y,Y,2,234000.0,450000.0,22500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307427,456160,0,Cash loans,F,Y,Y,0,270000.0,1298970.0,46786.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307434,456172,0,Cash loans,F,Y,Y,0,76500.0,163098.0,16015.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307435,456173,0,Cash loans,M,Y,Y,0,189000.0,675000.0,19737.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307437,456175,0,Cash loans,F,Y,Y,0,81000.0,180000.0,12658.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307442,456180,0,Cash loans,M,Y,Y,1,135000.0,90000.0,9580.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307445,456183,0,Cash loans,F,Y,Y,0,180000.0,990000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307449,456187,0,Cash loans,M,Y,Y,1,315000.0,1175314.5,38974.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307451,456190,0,Cash loans,M,Y,N,1,450000.0,545040.0,25407.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307452,456191,0,Cash loans,F,Y,N,2,153000.0,1350000.0,46926.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
307456,456195,0,Cash loans,F,Y,Y,0,94500.0,270000.0,15075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307459,456198,0,Cash loans,M,Y,Y,0,225000.0,959017.5,49095.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307460,456199,0,Cash loans,M,Y,N,1,382500.0,745429.5,24354.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
307462,456201,0,Cash loans,F,Y,Y,3,135000.0,1024785.0,57222.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307473,456213,0,Cash loans,F,Y,Y,1,90000.0,258709.5,20439.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307474,456214,0,Cash loans,M,Y,Y,2,135000.0,360000.0,23004.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307482,456226,0,Cash loans,F,Y,Y,0,225000.0,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307484,456228,0,Cash loans,F,Y,N,0,540000.0,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307486,456230,0,Cash loans,F,Y,Y,1,292500.0,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307491,456235,0,Cash loans,M,Y,Y,2,90000.0,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.0,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307494,456238,0,Cash loans,M,Y,N,1,270000.0,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.0,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.0,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.0,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子